smartcar/python-sdk

- README.md
- smartcar/__init__.py
- smartcar/api.py
- smartcar/smartcar.py
- tests/test_api.py
- tests/test_smartcar.py
- tests/test_vehicle.py
- Update readme with installation instructions
- Fix broken `development` flag
- Fix broken vehicle requests
> Various SDK Bug Fixes

- smartcar/__init__.py
- smartcar/requester.py
- tests/test_requester.py
make the python user-agent consistent with smartcar/node-sdk#56
> update user-agent header to include platform info

- README.md
- smartcar/__init__.py
Fix issue #41 with correct key.
> Fix readme sample code

- smartcar/__init__.py
- tests/tests_e2e/test_base.py
Asana: https://app.asana.com/0/478413718204980/889853378936203/f
> Update e2e tests to use Tesla instead of mock

- .travis.yml
- Makefile
- README.md
- smartcar/__init__.py
- smartcar/smartcar.py
- tests/test_smartcar.py
- tests/tests_e2e/test_base.py
See https://github.com/smartcar/oem-auth/pull/401
> Adds vehicle_info query parameter

- README.md
- smartcar/__init__.py
- smartcar/exceptions.py
- tests/test_requester.py
- tests/tests_e2e/test_base.py
Add vehicle state error code to StateException.
> Feat: Vehicle state error

- README.md
- smartcar/__init__.py
- smartcar/vehicle.py
- tests/test_vehicle.py
- tests/tests_e2e/test_vehicle.py
Added vehicle has permissions to check if a vehicle contains a certain permission in prep for Connect Single Select.
> feat: vehicle has permission

- smartcar/__init__.py
- smartcar/requester.py
Explicitly set timeout to Smartcar's api's max timeout.
https://2.python-requests.org/en/master/user/quickstart/#timeouts
> fix(timeout): set explicit timeout to 300 seconds

- .travis.yml
- smartcar/__init__.py
- smartcar/vehicle.py
- tests/test_vehicle.py
- tests/tests_e2e/test_base.py
https://app.asana.com/0/1135848224816825/1178967344640614
> add start stop charge

- README.md
- smartcar/__init__.py
- smartcar/smartcar.py
- tests/test_smartcar.py
Asana: https://app.asana.com/0/1185123266141337/1191525787597415/f
> Adding country support

- .releaserc.js
- .travis.yml
- smartcar/__init__.py
- tests/test_requester.py
> fix(ci): setup semantic-release for releasing

- .gitignore
- .travis.yml
- smartcar/exceptions.py
- smartcar/requester.py
- smartcar/smartcar.py
- tests/test_requester.py
- tests/test_smartcar.py
> Wrap unexpected errors into SmartcarException

- README.md
- smartcar/vehicle.py
- tests/test_vehicle.py
Asana: https://app.asana.com/0/1158554234878597/1199929686492380/f
> fix: battery capacity parsing bad header

- README.md
- smartcar/__init__.py
- smartcar/api.py
- smartcar/const.py
- smartcar/exceptions.py
- smartcar/requester.py
- smartcar/smartcar.py
- tests/test_requester.py
- tests/test_smartcar.py
- tests/test_vehicle.py
Asana: https://app.asana.com/0/1199874972215393/1200046735503443/f
> Smartcar exception v2

- .travis.yml
- CONTRIBUTING.md
- README.md
- REFERENCE.md
- smartcar/__init__.py
- smartcar/api.py
- smartcar/static.py
- smartcar/types.py
- smartcar/vehicle.py
- tests/e2e/test_static.py
- tests/e2e/test_vehicle.py
- tests/integration/test_api.py
- tests/unit/test_types.py
Update markdown file docs to match the SDK v2.0 spec. Most notable change is changing the parameters and returns of the `Vehicle` methods.
Non-docs change: Re-introduced 'is_expired' method and placed in static.py. Added type hints.
> docs: Update README and CONTRIBUTING

- tests/auth_helpers.py
- tests/conftest.py
- tests/e2e/test_exception.py
- tests/e2e/test_vehicle.py
Updated geckodriver flow to handle newly implemented Volkswagen Pin flow. Testing fixture should work now
Asana: https://app.asana.com/0/1200617420635813/1200661538477511
> tests: Implement VW PIN flow for test fixture

- CONTRIBUTING.md
- REFERENCE.md
- smartcar/auth_client.py
- smartcar/config.py
- smartcar/helpers.py
- smartcar/smartcar.py
- smartcar/vehicle.py
- tests/auth_helpers.py
- tests/conftest.py
- tests/e2e/test_auth_client.py
- tests/e2e/test_smartcar.py
- tests/unit/test_auth_client.py
- tests/unit/test_helpers.py
- tests/unit/test_vehicle.py
Adding support for simulated mode and compatibility feature flags
Asana: https://app.asana.com/0/1202541719267260/1202555728616889/f
> feat(smartcar): added support for simulated mode and feature flags

- REFERENCE.md
Fixing outdated documentation in reference.md
Changing info -> attributes
Asana: https://app.asana.com/0/1122465745219696/1203478035583499/f
> Updating References.md

- .travis.yml
- README.md
- smartcar/__init__.py
- smartcar/exception.py
- tests/auth_helpers.py
- tests/conftest.py
- tests/e2e/test_smartcar.py
Use the Retry-After response header from rate limit errors in SDK's exceptions.
Asana: https://app.asana.com/0/1203823333603132/1204206052757059/f
> feat(exception): add retry_after header for rate limit exceptions

- smartcar/types.py
- smartcar/vehicle.py
- tests/conftest.py
- tests/e2e/test_vehicle.py
Adds `get_charge_limit` and `set_charge_limit` methods for electric vehicles
Asana: https://app.asana.com/0/1204073873904879/1204302264096978/f
> feat(smartcar): get & set charge limit

- .releaserc.js
- .travis.yml
- REFERENCE.md
- smartcar/__init__.py
- smartcar/config.py
- smartcar/smartcar.py
- smartcar/types.py
- tests/conftest.py
- tests/e2e/test_smartcar.py
This PR adds functions in the smartcar namespace for Vehicle Management API.
Asana: https://app.asana.com/0/1205137826392826/1205221447377579
> vehicle management functions

- REFERENCE.md
- smartcar/helpers.py
The changes include: 
-Updated docs to show the function and the return values of the lock_status method
-Updated the map dict to map the security endpoint to lock_status when using batch
Asana: https://app.asana.com/0/1205281929337658/1205139255747898/f
> feat(lock-status): Added reference docs and batch mapping

- README.md
- smartcar/types.py
Added docs so travis will identify this package has a new signature.
> feat: Added docs to force versioning

- README.md
Asana: https://app.asana.com/0/1205997131005830/1206042566088090/f
> chore: Fix typo in readme

- REFERENCE.md
- smartcar/types.py
- smartcar/vehicle.py
- tests/auth_helpers.py
- tests/conftest.py
- tests/e2e/test_vehicle.py
`send_destination` method added. This is a core endpoint.
> feat: send_destination method added.

- .travis.yml
- smartcar/exception.py
- smartcar/vehicle.py
- tests/e2e/test_exception.py
- bug: Upate retry-after header to match API
- write simple test to verify
PLAT-203
> bug: Update headers.get to check 'Retry-After'

- REFERENCE.md
- smartcar/auth_client.py
- tests/unit/test_auth_client.py
Asana: https://app.asana.com/0/1206922837439776/1206699517630752
> feat: add optional user param for auth URL

- smartcar/exception.py
- tests/e2e/test_exception.py
Asana: https://app.asana.com/0/0/1206993255628966/f
> feat: add suggested_user_message to SDK v2 err response

- smartcar/smartcar.py
This PR refactors the `get_connections` function in `smartcar.py` to enhance its type hinting and parameter handling. The changes include:
- **Type Hinting Updates**: 
- Added `NamedTuple` and `Optional` from the typing module.
- Changed `filter` and `paging` parameters to use `Optional[Dict[str, str]]` and `Optional[Dict[str, Optional[int]]]` respectively.
- **Parameter Handling Improvements**: 
- Initialized `filter` and `paging` with empty dictionaries if they are not provided to avoid mutable default arguments.
- Simplified the parameter extraction logic for `filter` and `paging` to be more concise and readable.
- **Docstring Updates**: 
- Modified the docstring of the `get_connections` function to reflect the updated parameter types and provided detailed descriptions for each key in …
> Refactor `get_connections` Function for Improved Type Hinting and Parameter Handling

- REFERENCE.md
- smartcar/helpers.py
- smartcar/types.py
- smartcar/vehicle.py
- tests/auth_helpers.py
- tests/conftest.py
- tests/e2e/test_vehicle.py
Asana: https://app.asana.com/0/1208505982103877/1208604478475168/f
> feat: SDK support for new diagnostics endpoints
